[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "b7fb72494ff8d9e649ffb5c3576c444511032188"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "e39938e58a67ea27f5290ed8a859772cabdd04e7a96d17632a66895cc95cc9a3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "3d4eeb9853b348d134595455404bd138683c0731"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "b3ba0d4f9fb37a081b260c71e2d4738953cef4cbb961da6d69302ed759122abe"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "9eb591cb0e5b7c31edd6acef873f54d3f9d50df6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "f92b4ec977f27fad9024dd7c91109d947df39ef5975519ec5241f2d8f0bce167"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-build_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "381d839a27b773b4de28751bf0f5f48a3564c7ae"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "99c53b56e23e4cd2bc1cc14ad9a498859cec584d4077a9f8406ba84eb323e77d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-build_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "06267356704ca1b8180a0dfe7165dbb6b8417643"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "b4cc21a2ff1364a4c0d14d59b6ea4ff92a1ffa8dd61f388b7f82553cbd082d57"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-extract_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "58a8eb51be8ecd29b68453eba59dab14bd9c43c9"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "9f6636da56218cd7091b9e25e5ae1497cfcdebf5bb3d52fd94f512b26f074e32"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.1-GCC/GCC_support_libraries-extract_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
