[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "8f1329aae91c9739fa3dc5289e33b4dfe63684b0"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "324558802bf93053f8b1a1ee14906396358f495d28f45da0cf3d8c1aa6e5c5bc"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "2af254a6998ebd32728be22b6e43792df8d32956"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "b4ea59656856349d2b26d15954891c01760f8b447448c53ee0cdc890a95b312a"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "6e349af9dbebaded275d26ccd69980afb4748af3"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "1db659ea6855d4faace62c225d56fd8abdfc01aeedd19991c51370deabbd8992"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ffcf2fb24f8d195ec40c21bda28b9376ac88435"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "38cb6dc5dad1b97f09c67653575bc055a510d9b2731a74fdb44f76d4746f4225"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "115644b353f4e3cb0530d51588229e9218227925"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "764debc96c5cb4bf8f01fe441cca1cb5230ed2484d70c149ab545f505bc15fc3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "powerpc64le"
git-tree-sha1 = "ce19caa8b7fd7a7127883da87dcd464cce4d30a5"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "92e971b3646c715aa12e8e60da8dc9b33bc00f4d77eedfc2087321ca12a2666d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "5fb2a24f284326e5157306d253bb4cd6a579697c"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "fe0a9aacfac2991b82864f52d737a294bee40dedc5f00d073dcb5ad67480ad13"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "b66d0470730e4e4bb33a5e1fa5ad3ab2894ecbf4"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "ad3da979fad4802b87451a22600ebd598377a86a89309be4b5c4a1e0d420c76e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "234d22609f3252604ad7836e055e43344185522d"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "ad1b2b9789c6597f3c6c54cf48a9dec26af9346c183642aee2417faa48808804"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b9cbaa261530eff1df7171d198bc3e1ca0cb887"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d7c10b64d5b23f38f2cb1861cb01eb9d72b1df57ee3bab9cc1879e5a546002da"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ef699cddc59866bafbcc8c592b4d3ef8242b5c5"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "b5ce69298b7e5248021a3905b8c2ad41fdb0b6ad189a64e68de18ff21ebb350e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "4be1abb0db9436af1072c20d4afaa7f8b7f94b26"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "c33a2d099410a857055364a348107f906431acd65370152322781e366b0e9b1c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "cf82e3b888480ffb5384690fd42d353ebcf7b4f4"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "0383d54886f968adb3dcee1edbd090165d3022a6140722d9ef3722c5a4bd8242"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "7534949a60cb52b6ea278ae8c47d3ea504323ad3"
os = "macos"

    [[GCC_support_libraries.download]]
    sha256 = "4ee2f0441936c4f25b4ef424241f71cd8d6639a6fbf1e9bc2febffed4e6f987b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "4b4d77766bda6ae591fa6b89dbfcd40c07528ac5"
os = "macos"

    [[GCC_support_libraries.download]]
    sha256 = "764ded5e6a5370c9655f037c3275963c3ab0438ca80a9fe4b82b74fc90c169aa"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "c89b8c339af01f404134c7afc83c38dc467ff0fb"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "4d20f2d49da7609c2444dd39a8ced5a23dc0e092f0bc6efdec1f603f80466047"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "d06e3031f7962b1d6c6db09f4d47ea64778a5a75"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "3f8643435557e5e36d0fcb6d11d834f95dc668eba9dfc52feba6ac53f49463e1"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "5949b0b288546d29229f4ee1a3db3865a0decd02"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "37caa7b6f7a8cd96cd4bfb3fc55f543cb14fe3b360c334b622dfc459b130a377"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54a1de7d0650fc93dbd4b7e31082059a7194bd37"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "4d66ee1ecc57542ef82cce9ebbc3977fc5bee86f63e487e82ca75a8c2fb44ec5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "086c93b532447a4e0134151134b529bec132cf34"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "db17b29cc3554861ebcde2db94009b8eaa9e0093b275458a7130c8ff3387d927"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "8221c4c8b08ad1d9e4282f9cac1947e593c63721"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "d70c1593ea8d4c0e4366c886e5be9912f97e8b3f97f6b9e1924089caa6610493"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "a1e02a8c76d87d966c1722cdb8d89fcbba4a6abb"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "2603225407ada3518faeca0a4de3730e20f32de9c3dd998d45616e226fc6db7a"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "5a0ce7a993cfb0189a5cb55453d84b89f10a29c3"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "391f7babca88366b067fe82000e878b5b323673e0bcc55ab6a5667f687351412"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "a798622a3ad4da369599bc2393c945c8fdfe0b05"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "850a692fbbde57e80a388ac61fca44f89bf07f7e2bbb08d95c2952801ee09074"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "800e0077e82410fcbcb399307ae3a5e38638bba8"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "2d0b221b0bca3a152227f3ee294b7faf29d8a05dfdc7f52f66576bd4ccdda5c7"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3194acf4c6631667534bc139b9374a974e50c94"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "609f03792de77dd1079550616d228dfc9f70903dd817035fb7ce22c9bf4c4f39"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "8c9efdf524fae9b78c9ad1330b39ddf7cb665e94"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "39a08cc0e0bfb7ede5fb608a72390fbd89b301096d19a010673562cd37a9bdd5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "e180b9af9020d44312a4fc4322685b9173d085f2"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "71f3da7bbd6f2585915f3a8cd44cbd2683f66c689df0dedc563b0c19b388d027"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "63d635f47d85a78e36c3d4f2bad62ab974aeafa0"
lazy = true
os = "macos"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "951a500135f86cb3ae07ad9abaf89fc0963552c4dadcfac1860db32577e952f8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "9561a7ca2fae9cff2c8c8707bb3d10464ac8e5db"
lazy = true
os = "macos"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "0852c2aee04240b176aa5f8d2434f75dad3eb389a33683afc16ed3698edc9dc0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c6886c47ae54afbe00bc2e87cfe27736c446c180"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "80f8b2af8f76f9f0b7f06950d30e2f5e073864f434dadf79b0be12a892544f8c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "284821da703bd4f59d5d69bbcf7cba07745a085f"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "6a4ac33e85bd56cb9ecc4d85c89a7457df06486ca0649c4be003446c87a4f045"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2893c8485e1ee62b8cbe54a0138170903174bc51"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "5ac36e519326e6a97a415c1cde12e3c91f11540e61f8cd440c69a16ecee938d3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f32473c59381cc806a86ee497722e1be8fbb8293"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "7958d291c8edfd61533d578dd0230f1a7a7787f3d94f53b5663b807293a4febd"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0fa1970c014c04f000fe4ef40e4982b9a0c3d42e"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "b93b83331560486bf75e356b00f2617749704733f7f17b0619b16bedc0c86fef"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "0c8b88c65409ae9077e46d2ec220742edff51af7"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "6c4076311183f4a7bce1d313f416dcb5b6ffd0ff28adde3eedb0ac62858dc1bb"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "21c4a120adcc25bb50cc10a5ed4aab07e02acc63"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "99dc990fbdb172494128d7925f7052b4e5ff78c726be821ac46e59a65376a895"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "98a09b8019d542adc540d07d30657cefaccdccc6"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "f80e0eccc77a9775815b16a9774f3a47a5a5b3619de0a9df515e5c080150744d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a8afee13a2e5c512829504776637ee26271eb791"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "f5e56647054ddcadc2c29bfbcbfb1fbfd2ca7feab8d96db552aafa1237535b94"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14f560ec5d2d78a71f7ad1d17086e83de8e5862f"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "11637ed4eb7035a7c7c30afd05cbe1237cbe309c44f47f12f834ce0936d488a5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b08f86ea283ffb6d4725fc29196f8ad6f6cd6168"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "ae5ab27a67bc95087083dcf6f259c07c73f377832caab178c269d42357133a3b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "04209536c5f20e9f77f91d895e3607b9b3156e17"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "a1cbba941cecb2dc4281f6c923a0d52196d4bfe9b1db6552fb7f9984f1104744"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "7e307b309f0205d14a5847d6fed7e20d5aecd482"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "9367a2c97bef3285ad34856bdf224a8a7d97143b5035de3356b95289bd00d0bf"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ddac7b6fb8e0df5e0590fc28cc17c46da3377a98"
lazy = true
os = "macos"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "b02da56043368d2acb3de72e30ecac4ab914affabba5843ef3004fea884d4f67"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "cbded271f6178b136278b6ce85dc89ed5c39a2e4"
lazy = true
os = "macos"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "9434c3d27663529e71ba80a172bd089ec8ceeffd93bfe1b7a7b5ef2afecae866"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
