[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "c3410c73068d9456d619ebb7ff7678e0f0e3a53c"
os = "macos"

    [[GCC_support_libraries.download]]
    sha256 = "cb39b2d23b16c857aeac4e21617716cd56846bb021beddc0a4b330946859884f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "675200a94ce1a0b7559ba616daaf45b7156cd801"
lazy = true
os = "macos"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "d0e604d1151874a1bcb00617ef0ce10918e186c7dbe7cb393d96296d46acbd0a"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7bfdc0538a527f64a3b47fe70e9b133b181d26b9"
lazy = true
os = "macos"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "6769d36bdcfb495172dc90acf4b63c223187e9f8bfdb6067e2a585e609c6c913"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
