[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "6160a38c90f05fa5e21b0eb38d0cf9c4024b6f76"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "b20e1b40d7fcb7e90933e8a3376c9aa01a3f39153931e2b66328ec56c5cca413"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "0bc733876ff1b57ae05ae770993b1d2de849cfb7"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "fe9622d48e47ee7ea95515bd489ca54f9441cdb4823bd3763d8aa18b601c461b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "f0d5be0373a6069027620f0a6e557226c709144e"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "ab463377066fecccbadaa0a30b7cf0a09e36f9be1eaaaca3729a18c1880bcc7d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f5436a5cf81f9a1665e6322bd6233b3e5e194bdf"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "f0b50a7df1d391d976e4c358a026b56193715908a6bc173ea3ef71fb15c5eb03"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea07d3d5d21c24ed18e9fdd487c94fb29252a08e"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "b3fef11b02601e27cb3871a348ef7d825b95d69a567a6e002bcb8fb08c95dcc0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "powerpc64le"
git-tree-sha1 = "688127734bfd88b6a50ec2648ace2774b69f09bf"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "6404a04b79c059d2a301e40399ea774efccf9b3297b6fb8e864f5d73f76f7a00"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "f83055d26854d8f8410dd7e940449a77bdb4ae2a"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d8d54add9294bd88c185f344a087b852c19f24769388e604c9b6ef7db52d8976"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "cfbae392d302b384e0609af6d7f0b1968762501b"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "42df8bd85570df7166437e26520fb1098d440a195d67b3fa25daf4db502b2f33"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "40577dd9798837b172ac31157df0292164b02b90"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "1917c2996869150d3d118364f39c5cef4e0cdd240ecf57c3d81ebc59f23269fb"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d3ccdf689bc8e1bbe4ff4db730a57d622ce8627"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "c895fde71bac08afd4068da8ceb9aab95aa79be9146c2fc3dba7a98ace5ba0cc"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1378d0488718ffeff30c2317877ce74b2dbd0919"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d4f06621668cc5c845b5f53b2fdaf87336cdf2875db3fe53a6b2e0cc3622065c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "86cdc7deff5b4912e3879f00342969c65e508bc4"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "dcb3c88a9e573e6d912cfb24f2b697c75d15dca522028818d0740b38c12c34f6"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "c6fd36cad91a655f0635a6b41ff1602e3dcb3153"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "c6d4fc93773c044b4ebf350d20150ab434491ac9bff64f035bd99db01ed064ca"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-v9.4.0-i686-w64-mingw32.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "b263a61b215b16fde4e1f21be7c1b97721b45157"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "192d5144ef749c2289042ee78d552c4735f97536309f20f6e3990e5b16cb2494"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "504965f25c0ed474965947f1dcb1559eeeb23d55"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "f247b59a467015d2e7fa3411521c8b6a8b4d6c04872c4ad99727fa95c1db6603"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "12cf00ad5a36ac11b6bd46120373a8285baa6ec4"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "ea698d42c140911d528b2fa7678b0b139239fdf95c79b5147a72a932e69da39d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "48b6bd960424934dabeaf1f4047e74c3f26815b0"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "05cc96180ea7d42b98643d8b7f29bb13b3302c623304449b84d0544242ce543f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0b9371405b75d4741fcc6ed6fe53ffa8f358555"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "10ad4b0dceff3be1e904a4e93860c3fd458650de4be9a6864f5d4588dd44688c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "81e7b20703288c8b5205997a9f57e6d6baed5972"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "210cc8f4e4d6940368f8d3c7888ca9867c9a400ea888445882eb850a4f6ca82b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "f9cbf1f453cb18a89a1d16028b61105dcc3ef9d6"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "abf7f04c05fd01bd0a8f3b6987b81a6461bd8cd3c7b1a4d1b2e2ee800b20ad97"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "2273e91177944b9a92fcf003a86b455a485c5cab"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "708cc51d181621b3a4741bb520feea75578fd1b44ea693a9fcd377a2949c1e16"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "c83b6eb606aab5d7cd320443f5c781c08cfcb968"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "edf7115bfc53975d20e199d97bf978d17c9b38eb35fe98c7efed892f50db979a"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "abda826818d67e642fc991a159e579c74eff81e7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "36cb1ccb582343bb48b84f6eb387331f6dd45c24e74577b1337568399c2f4bc5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "184ff1d963481f9e097ff81bff5268779525309e"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "976df9cd9de568096870685688e3cd8f45b3523d64b2d88d45379c0c6b041ee3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "56d5cf49b4f03447a6b4e10e02fedf823511b554"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "658387d1c6b9dd9b58f4fcea092d8f43f53d70bbb233878fbbae93994af1feb0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "910074ac649906c1cdac1fe8e80de171604364f4"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "7131e4ee82dca5962a44acf198ecb06d90b1baa6b1a41f40ddeeb5757d28be26"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-build_log-v9.4.0-i686-w64-mingw32.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "90a9c158266b83aaf6cd19b1b8b3093aeb849952"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "a50d4eabf6a3b074d4f53eaab4e6d5182873e83d5682baab4b102cf5dc643b43"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "c5e3e137b4040745790dd7d8237389212fef424b"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "e59ed67471a82bba7ab58a50d8140cc2b471784bc1d182e2b73702013d6e8ab7"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "546ad7b029c2f84525f2644ad753259647f467cb"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "b4b5066a1e3e0f09ec46e70e90c75fac265168e966444a7911a0eac1f32ee51e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d724cb4fec5d702237e4ab38e693f71fbf574693"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "178cbd1d4b43c3797d164df6acacdc9e633dffa2fca2ac81aa2abcca469e5d0c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d03394f8a3b2f4a5d746e0313881eb7af3858eb5"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "738f0a656fc8ffcdfb92f4273fe74a6d99f3822b7cede1b675b1d4d4078b3c66"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "d757bc375638c0f36a4cb142f569dcd7358ef428"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "2ebc47753c6c4c0f2d17c36238035d22e75d53934fe35ce0cbcb408007a9b14b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f4672b6995d36791b09797cab1ae3749ccb87c4a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "cf1e2cd2c05eb191cf602b41dddbf8d1601debaf94f8cac0e5382dc3e60cec3f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "eacc58af2cfde9fff5e731ebef5c3d91a71603c3"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "530b65b59585bf0cc7805354dae20015e9b6d84792299e4bebd560e96a57ad6e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "837d8d6a9b9f3b0a0d3015409116204154e48942"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "801d2745715e330934be5984fcf836ce1f030cc399906c1f09811caeed1a6d41"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef434e4a534e331b2bc34c5a926cd9c183f806b4"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "c74be10730ed37d74e3f5d6676e44d350461ef491e7f4eda052daff53adad171"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70191dc5fb60d643b9eff47caa6d4eb5b75f1820"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "0ee1bb3b8ff139cb2a5dd6bf69f8eafa2ee79a960c9ab4ff0e2f3804cdf39387"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c8d48123516b5cde5e281cec1acb308e16f27036"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "119cdc7a2ab206a5ef6eee96e0a29d81bb59c445a00e26cc140c94893fca3a1c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "df6b36e6f8e84831ed5e7d4404a39671805126c5"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "8355df071ac08d14da385ac21b8993830a9b1ac8b7084b90ffab46c23bb8d2b5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.4.0-GCC/GCC_support_libraries-extract_log-v9.4.0-i686-w64-mingw32.tar.gz"
