[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "8f1329aae91c9739fa3dc5289e33b4dfe63684b0"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "f5570286d96bc64c0944bf37e45a81c74065654e00389d5c1b596a84d39815e8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "2af254a6998ebd32728be22b6e43792df8d32956"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "eb5f23d81e20adbdc1c7c09fde11545b11000f2df7a495587b506663799325f4"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "6e349af9dbebaded275d26ccd69980afb4748af3"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "db45ce12ed97d3f507044f0f1723056088f017742b01d8756bf94567ab9387f8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ffcf2fb24f8d195ec40c21bda28b9376ac88435"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "91c5b0178b5d147568285b6ef5e6cd6a38eb6fa06527ff9c8c54e8ae0b9c5bb3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "115644b353f4e3cb0530d51588229e9218227925"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d02bb9af8cfcba098a08e09760004445a2c065ce93e23565d45244b8463314c9"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "powerpc64le"
git-tree-sha1 = "ce19caa8b7fd7a7127883da87dcd464cce4d30a5"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "019803c5ac4ec885cb08492597ecf82c9eefeb475ca1239fa26cdec2ac1f6d19"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "5fb2a24f284326e5157306d253bb4cd6a579697c"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "017c8452ea2111ac4bcac2c6a2f2a6099c116ca7312f2328634cb0177c9db8f7"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "b66d0470730e4e4bb33a5e1fa5ad3ab2894ecbf4"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d0f2051bcc2831d9712748521e3df1501b315afdccd0b86e6d1c6525745ea43d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "234d22609f3252604ad7836e055e43344185522d"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "4d28f57ab53f02c7c89ae771e52b33e578de6c418bbdd20b76ba2268077400d8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b9cbaa261530eff1df7171d198bc3e1ca0cb887"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "f7fe0bfdc8f8810c7b344824c983cf94a03faf108ccf881641dfc952fdab7f8f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ef699cddc59866bafbcc8c592b4d3ef8242b5c5"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "3dac9002f29ce8ddb21d6bae503ccaad1d03da8e06b139683c4321bcbed2c2ca"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "43609576a29ad1fc4c435eedde083dba0070cf58"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "f92ec68305d8492d15ae9e0b6ecc73b69452e3e6bce06e72c98418797b6ef32e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "61f17ef92f644cdbc4bf11857e6322297ed93c62"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "c25e4a2909dfe6a9aa9321f7c3e55ed0df7536b8075fb32a7ac9232d95fdca0c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "6c3f3037a21635d798872f48c45829f72dc47422"
os = "macos"

    [[GCC_support_libraries.download]]
    sha256 = "8e4f374b69d757bf94ed376849b6650fe7cb3816887537d9f4ca51c176b9f556"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "4aeba488750a6ff574fb88fbf88910ee2bc10406"
os = "macos"

    [[GCC_support_libraries.download]]
    sha256 = "f5429be11a38473f5ac20b3561a2e0e39d19ec8fad5ba3f2fe9bcfc78232ab61"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "123b1469f104d47d9835925c9212ed382a682fdc"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "b7fcd87be2c35d508cfbfd17e107eed2e23fa001ed7ef28e75bf2ae038d06f6f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "1967cdf47d9dac8237735fdbf6978669afa3c74d"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "1c213537a13cae897da381fb5e2ba1bf83e9d55d21c1d36f3613737b0b07a975"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "6f349c942500f1323f62d58a129de8b3557a4f93"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "84a2a61a8b8670540d26be092ae3b87bbfae43d0856f1fc9ef3836f322d98fd0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e06e2c2b7b72e67dd5ae7f31663561e1823ec64"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "e565127d2cc89e47acabfb14496afcc37ded5dd271727cb4d18a1489684f4123"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18d49b663474679964ea4161c5ee6250353f4327"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "e294298fe17e868e34f7601445352e51ccab2052940145de0dda7a5f6d91a4b5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "82dc462e262db402193e461fd252c4aa285175fe"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "1a58d2829725d5d6c4fd79a6772cb5328b3cb78306e969b482845cadff79d859"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "ab907ee1cc8a1f3fb4ebdf36727802abee081d37"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "2c439c5c99c8397da7660242cf191c1940104a4f3141ef7927b5d2648da1e58e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "5a893a577c6400c83b0eb5fb304a53aecc0bb2d3"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "7ac687038f3b43df733d60f05872176736ba2901bcb7c2de24beb252f23ed828"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "65d77e77404b160d1ac8f02f7b08c820d2e10896"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "68d65b302c0e33c56145302e75c9483b026e39fd89de9e2f3636420d18cea189"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b4f0c8a2d98d45e27b9b2e6cb4c7f7fea60bf04"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "25aef450fa75ad6c8c430ba7f8cb79c448a9a3c9dc775328009d175946a9ac01"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "684c3ff5d3794230baea4debf77f53a3d9815bd7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "95c903983f18cfc72fcb0a0ab891c81649e3e7831b15f052c39b7e7ecd6a7178"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "b77e641837ba8d30b102a04db95ff64975fc17b7"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "9fef7dcdb8e91f3911e4644c43a1c120a16b2309f37a6764ca9f4fa8fbc5592b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "313c2370f73b9af7abf8b9162aade7725dd9919e"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "76084d8896eaeebfca36ca1a7b04bb3b608c01fba4eb0a479f44fdfce80ed3a2"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "6915231346968d4501e98fb958f56ec0a3551ab6"
lazy = true
os = "macos"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "63413441c2a2237493ce2ee684c3487160fd562f94a6d747b5c47c0713095b89"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "6149df285c0836cb668d75a22c8340721dfdc05b"
lazy = true
os = "macos"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "92b0e8ab2fb33be59749d6bb5854a5d28c2449a80545814d5ffd416bf7b5b07e"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8e4b3f6871436359f288ef639eab166edd43f715"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "c5557335cb6965c51cb585ffd8a6c62091351aadacc3bc95482525a12b8b26f0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "0ab863786e9a5368e14c1b84e3fb40c4790e7600"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "ee231af29c2fa32d0d191eb555bd304c4c34cd7b3894a8bbff226a1f4bdec9fb"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "df9829f57a91480f40db791249eb5bd438114865"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "2ca7be42c794edc822d2a64d4f8fdcac6543675357352b2b1f5d0736c16abcc8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46b69707e9c509355eac46e00ec4be2c0b4526e2"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "12200e27a415e6bad3af61efb69a22d1ee9374c434a3efa037a12abf02267319"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c48282f9d7e25b200a7a14cfd31d038bbce3a3a"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "1165413d0c9b04bf1eeb9bde385bf557ad04e0e5b4a85a55655fdea03fa043ac"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "50beb73573d3dac78a136830827f7ea39a7af583"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "b1b7a65aa9dbb1122ac302983ddb77e1873f897ee7301636ed23740e1e1246e9"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c369d86047e747dc26e957f8874f0d8a1a2eac02"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "18debf9f479d8e7464ffcbe5ec776b124f40d7ba9a26e31eb35ef987040e748f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "5f972cd7994c597df18a8a44cae261d654f99847"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "ba755b4b9ff2527892af297fbf4c96daecbc048854bdbd341109f1675eef7edf"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aa4f91bba01c9c887522c7cce38bb2194d8a9724"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "af96081be9d686db37f92b5b923b0a7041207c939ab70afac9593f94acc99a50"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c666ebbe24be89d9056de93ac4859698f385f02"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "3f07b8fa003602a170360ad8fc3bf4b1c754ef6403dbe12e6913e0056f53480b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9ee601afef3b3d4a8f5256835902de53dafd64d"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "91529ec6832b9e6c92085ab872ffa0647dcee32563d3408f1006ba479674cef7"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9c8e842774ece3c452dcbcbb5e62ab683da23ec3"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "05face2a29c7245c4b7d8992783eecca3561bd669ca9ae289f5e4df4675543d7"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "ed9ec232251d833421767a7c9c0ea3be83dad0d3"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "e814710e8af5c8c79e11da7acce723defca8cc155762f9b7e0261a49e91b8168"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "faad57d6bdf2fd5af5231cc52a226bafe865d87f"
lazy = true
os = "macos"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "2496d99ace04b4cf5af78b6fb0603eaf42e93e2057a4ff9a4953339dda7a7633"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "8ab826cfd9b1cbcdb7f20b6a221778639c6641d7"
lazy = true
os = "macos"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "58b9438beb8c618206a631c19a4c5b8ef1396370bcca75f07a26eaf3af774bfe"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v14.2.0/GCC_support_libraries-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
