[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "93ac3df0673d6191f1feb18df9d039334dc92439"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "f0632fcf70c288c2e120e9d6106b5d09b3272e443d7a8bbce646d07e13a12e85"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "c01d496997c6c747555f3c02165ba34352fe1ab2"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "0ee36836f5431935e7ae10016031ce164c12c2fb6d8d0428991f23110b2436e9"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "77f019068f802145a2d17a898e6fec7f54657ca1"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "e7b34976422225d8b0d5de0fa1a045af04be0c6e5c6ee62826a2872e80bc930b"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ec39cd50d8bf78110b744c15e7f1d7ca9a57cf0"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "d072ddec8835a19a0f414bec1ff15bec33c6e0747ada900c62b07e5ce1ef36e8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63e7b26242b30b18c12950eb1288ecc5914f29c0"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "767c816b108826c660bca67d24268bb2e96323b1fe6ad7572467152e33766b01"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries]]
arch = "powerpc64le"
git-tree-sha1 = "1be71079c93d51834b5ea6e507606de66a8f01fe"
libc = "glibc"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "ae5dade2bfddca6799068ae6c21e5443165a8f06ad22c0c393c42ad659d07142"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "719d7e3f1e4581e2cde796d2c836eb835fe16dcb"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "44000cd7f941914d6cdb9d7ee8ea73d053be49e35908d9562ab63fe26ac26be3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "3cd36dc06c187e8b1320c5b4d8bea5ae34219a7a"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "bae9d3ea99e6710c5fc11232a5eca787a9270e8f58feca40c5066008e2f32ba5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "aarch64"
git-tree-sha1 = "21fcbe7f4224d34fe93635d49fb068ca46036165"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "fc4aefac8331dd01467c02a03016d1a77a54c4765755cbfb9e26e9b678190af4"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c94c1ab473197a718b2e2345c48cbe22458fc3c"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "e08af02be297dcef1b943716f79e30d0691e37b78bf88ebd34fd7ed9030e2478"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "10e6c04fb380e4fe106eee04c4009b6a9750d008"
libc = "musl"
os = "linux"

    [[GCC_support_libraries.download]]
    sha256 = "77b63fe2afc7b6216fbf2f3f9b854842007973dca7a8606dabeb2640bc3024ff"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries]]
arch = "x86_64"
git-tree-sha1 = "2f7a0302756d83ebbf737fc47620b1838482b198"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "81a7daaa7589e01fca0e563ea7e5a93bdbd03b2215a865b33e68b494d0e616ca"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries]]
arch = "i686"
git-tree-sha1 = "dc77147f14c4d5c8c7e9b9ed0752940f00807728"
os = "windows"

    [[GCC_support_libraries.download]]
    sha256 = "03011b5b5f846cb7b25979eb79bc5add99fe7ff0c05bfa59fe3601434d08fab8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-v9.1.0-i686-w64-mingw32.tar.gz"

[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "452fcd4873742a111eca232eb513cc0454cc2771"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "be81a806e5bac58ba45925d38f51864e7c99d79c4d05a1d368a66dbc3954e12f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "4a250fe30b4e46797ed1cb56ac41b8120ddaa8a4"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "d7de6c4c2c8106d7e7ccc1cb14af4b5f64c6097025f45af990b38f7f1af35e02"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "4d0668254cbe04bc3a7ff585580cad611a8d5a7b"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "ee041820cfefc2ff2e6932092d0b30bf07268e67ca197fba15428d678712651c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6539ec0deae8052f09e03c9f3490f40c9b004760"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "afaa8ba9d106cb71eff45c4e8c52d4eb216fd93c4043d98aeb15a37c2e7c6d72"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48ab02beaf265a5a0746d388ce0ed8c3838b3b61"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "77bf181226c74f2c044225609d94a66dc1008bc49702b45422f19e87bbebded9"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "50cafaf60a5ef88da94ee581aada993f606bf436"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "16973220060a09e065850470acfafcf0154a351c3eb6e85fc807c5c3f9fd4ec1"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "7fc91a4bfc1cf90bd7f457cff5ab7c84ce168b0a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "be7fb6f078052d6008150fdd8c31e95baacc4ddb30503aee50681a1d1fb5de06"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "a3f8ab305f7f3750bd67accf9bd1868bac1f42ac"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "4d14fbb2b9be6b4eec31bcd4b0b41bdc9c4e4012883e743161aed6ec5c39a4f8"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "c19926d76852285d6723df7c15f3e8c7288ae428"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "c1f0720020c3fc3754bc1560d33f8058169ab7b937368d920a502d56bf8688cc"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56a1300de92cb559088b61133e6ede4e7c6da210"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "93161ad88385cc5ce1190a2e4e2771e3c9ffc6fc94d0215b6e2a9ba94b8d8a33"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3aca58e29d02139ada4502664d021cb48618767a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "63e4ae4679efd8e660b8d0200a704512f0741bb16311e49454a471533d409a01"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "e85245541c57aca4b85c3848f6e7d07b7d87d556"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "45c6264a6445c8f667a7393d523f4c1c653d6a7c29d8b99723b4e6d8e5ac618d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-build_log]]
arch = "i686"
git-tree-sha1 = "ff6896d1656156031fd157e7e2df0464d613e876"
lazy = true
os = "windows"

    [[GCC_support_libraries-build_log.download]]
    sha256 = "2528579278b213456c2a590e704e2545e606e0238058e4870a5c132a9919df0c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-build_log-v9.1.0-i686-w64-mingw32.tar.gz"

[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4d53d92b690049f08a9cc3d4e03d5ca54fd25fd5"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "7248cfa118ccc087dc66d96fcf9446158c24ffd6edec3c24d60f19f54d40dec5"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "0d041234067b12a207ede4a023efb3755b9edbe9"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "1c488c4e52fb34a5ed44b9a9cde1c568770733736b24a948f3fe8a910644ff04"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "08b847320661c922de20b3104ea170885114cad1"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "afc48539b950a7c56379a0e934b445040f0608730ccac96148274a3653a351ee"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "300447dc7b215006549659631b43634f5355c819"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "68095ae33d5df304b67cd7b044dbd879ffd22dfbd0570602b9c27bd254a32da1"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "927ef82f13c10518dbda1df58a0aaea93fda6cef"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "e006021f91423e9a6b59b686fa5ac0ae2717d8ae72e41849704ef5ea9f489fac"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "b72baf0674f3cad6862ebfe77a87244d7a601dd6"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "41997a7b7728996fc1af8a092a907aa8ee8ab35929dea417fc209a32fa82df95"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e0b2f1c98602ee9a891427379c179e980ee55d5a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "747552697287e3b54053cdc63e21985bf46945794ea44e84226ef84e0bbcbe3d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "3806785b0a99976be15f6b4a8cbb8ae7760891a0"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "7f88509fe1cea053560879c8050d3dd451db008851cb680a98e6b27073dba85d"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "87bc447f660defd94a149019f99e6e68d7563de4"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "133ca706e6a3ac612e57406e2036b2daca3abdf6cd89b08397dc017df0f8c09c"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15df6184c11d9d7331217b15a535b968facc60bd"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "fcf29f8b68593c88231f92d3c30031e8ea389467860249fee0f847bcc4736c1f"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb36b6e61ef20f692b87d4f24a13aba7d150b541"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "1e140252652317f2583bcfa736c9e41c74e955b2d6fbd777055f5bc5c0446ebd"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bb4da72a2f32168300cab8b4347f5323f0d54133"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "efab633fc2b2d65607a371d132af29a89853e588749176ad342f25053e020e13"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_support_libraries-extract_log]]
arch = "i686"
git-tree-sha1 = "732e9113dd9b5ac102f3924c695903de4537eca3"
lazy = true
os = "windows"

    [[GCC_support_libraries-extract_log.download]]
    sha256 = "53ebdfbce4e274640741a45dc4caf48fca26cfaf5a4e59cab67af93c2ffa9819"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/GCC_support_libraries-extract_log-v9.1.0-i686-w64-mingw32.tar.gz"
