[[support_libraries]]
arch = "aarch64"
git-tree-sha1 = "b7fb72494ff8d9e649ffb5c3576c444511032188"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries.download]]
    sha256 = "573bd9067c8770ac417d264bf49959f5db12755452185cf5c70f17d280137276"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[support_libraries]]
arch = "x86_64"
git-tree-sha1 = "3d4eeb9853b348d134595455404bd138683c0731"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries.download]]
    sha256 = "bfc760fcfd33e1eadeebafdcda19560aa619256ae76d7d2a38668064d5717928"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[support_libraries-build_log]]
arch = "aarch64"
git-tree-sha1 = "60b152d12d84df566301dc9cce7bf473fde03254"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries-build_log.download]]
    sha256 = "89b8c61a6978e973303ca1145e9287bf295ed8e4e750a2754210a025ea403530"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-build_log-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[support_libraries-build_log]]
arch = "x86_64"
git-tree-sha1 = "3832fa2e7c9f18b441e4516282468f8265a62a31"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries-build_log.download]]
    sha256 = "6b1b4536d7ad1433de8fb4a581002e2b40d3ae576f9d1aa245dc84f1058431d3"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-build_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[support_libraries-extract_log]]
arch = "aarch64"
git-tree-sha1 = "1537903f1a46b2ff9601eaac3692818015a05f75"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries-extract_log.download]]
    sha256 = "8c1bf16f5ee84314e7cf97e28101a7320aa25c1925c91be3d06546de958b4ac0"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-extract_log-v9.1.0-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[support_libraries-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8a7a8ceb1785a13b260044eb45acfed2b7665fc5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[support_libraries-extract_log.download]]
    sha256 = "c89692f6a80072e4e270d6f044071c7ea1b5d35da9e321cd79aa9fb5c0204fd4"
    url = "https://github.com/staticfloat/GCC_support_libraries_jll.jl/releases/download/v9.1.0-GCC/support_libraries-extract_log-v9.1.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
